# required for test runs with web-test-runner
# possible error:
# 404 network requests:
# - _snowpack/pkg/react-dom.v17.0.2/common/index-833aa646.js
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-sources.cjs
