# required for test runs with web-test-runner
# possible error:
# 404 network requests:
# - _snowpack/pkg/react-dom.v17.0.2/common/index-833aa646.js
#nodeLinker: node-modules

# required for snowpack for now, before tar dependency is released
pnpMode: loose

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.0.cjs
