name: Notipie CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install dependencies
        run: make

      # Add caching
      # https://github.com/actions/cache/blob/main/examples.md
      # - name: Install ui dependencies
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: make install-ui

      # - name: Install core dependencies
      #   if: steps.go-cache.outputs.cache-hit != 'true'
      #   run: make install-core

      # - name: Additional steps
      #   run: make copy-example-configs

      - name: Format
        run: make -j4 format

      - name: Lint
        run: make -j4 lint

      - name: Build
        run: make -j4 build

      - name: Test
        run: make -j4 test
