name: Notipie CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'

      - name: Install dependencies
        run: make

      - name: Format
        run: make -j4 format

      - name: Lint
        run: make -j4 lint

      - name: Build
        run: make -j4 build

      - name: Test
        run: make -j4 test
