name: Notipie CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '^1.18.0'

      - name: Install dependencies
        run: make

      - name: Format
        run: make -j2 format

      - name: Lint
        run: make -j2 lint

      - name: Build
        run: make -j2 build

      - name: Test
        run: make -j2 test
